### ISSUE TITLE
failing to build on mac

### ISSUE THREAD

**Issue by zakrn** [pravic/rust-sciter#6]
trying to run the example in step 3 gives me this error on mac, any ideas?

cargo run --example minimal
   Compiling sciter-rs v0.4.0
src/window.rs:82:33: 82:37 error: mismatched types:
 expected `platform::windows::OsWindow`,
    found `*mut capi::sctypes::_HWINDOW`
(expected struct `platform::windows::OsWindow`,
    found *-ptr) [E0308]
src/window.rs:82 		Window { base: OsWindow::from(hwnd), host: Rc::new(Host::attach(hwnd)) }
                 		                              ^~~~
src/window.rs:82:33: 82:37 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `sciter-rs`.

**Comment by xieke91** [comment]
when you build it on mac or linux,the struct OsWindow do not have a method named "from".so you can not built it on mac.
[you can fix it ](https://github.com/pravic/rust-sciter/blob/master/src/window.rs#L81)like this:
```rust
/// Attach Sciter to existing native window.
 pub fn attach(hwnd: HWINDOW) -> Window {
		#![cfg(windows)]
		assert!( hwnd.is_null() == false );
		Window { base: OsWindow::from(hwnd), host: Rc::new(Host::attach(hwnd)) }
	}
```

**Comment by pravic** [comment]
Thanks for reporting this. Try now.
