### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xieke91** [pravic/rust-sciter#7]
something was wrong when i used rust(64)  to build examples.
$ cargo run --example minimal
     Running `target\debug\examples\minimal.exe`
error: Process didn't exit successfully: `target\debug\examples\minimal.exe` (exit code: 3221225477)
Segmentation fault

**Comment by pravic** [comment]
Rust and Sciter version?

**Comment by xieke91** [comment]
rust->rust-1.9.0-x86_64-pc-windows-gnu.msi
sciter->3.3.2.6
 it can be built successfully with rust-1.9.0-i686-pc-windows-gnu.msi

**Comment by pravic** [comment]
Yep, windows-gnu is not works. No idea why - [this](https://github.com/pravic/rust-sciter/blob/master/src/lib.rs#L104-L105) import entry points to null.

stable/nightly i686-windows-gnu works fine, but x86_64 won't work.

Anyway, I suggest to use the windows-msvc target on Windows.

cc #4.
