### ISSUE TITLE
Implementation of fire_event

### ISSUE THREAD

**Issue by a-nigredo** [pravic/rust-sciter#9]
Hi, @pravic.
When are you gonna implement  fire_event function for Element?

**Comment by pravic** [comment]
Not only fire_event, actually, need to add [much more](https://github.com/pravic/pysciter/blob/master/sciter/dom.py#L527) functions.

**Comment by a-nigredo** [comment]
ok, I see. 
Do you have an estimation?

**Comment by pravic** [comment]
Do you want to make a pull request for it?

**Comment by a-nigredo** [comment]
I'll try but can't guarantee that I'll be able to manage it since I'm newbie in Rust.

**Comment by a-nigredo** [comment]
@pravic I've started implementing and have questions about the next signatures:
`pub SciterSendEvent: extern "system" fn (he: HELEMENT, appEventCode: UINT, heSource: HELEMENT, reason: UINT_PTR, /*out*/ handled: * mut BOOL) -> SCDOM_RESULT,`
`pub SciterFireEvent: extern "system" fn (evt: * const BEHAVIOR_EVENT_PARAMS, post: BOOL, handled: * mut BOOL) -> SCDOM_RESULT,`

Why do we need raw mutable pointers for variable "handled"?

**Comment by pravic** [comment]
Check [this doc](https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-dom.h#L668-L681) if I understand your question correctly.

**Comment by a-nigredo** [comment]
@pravic  I'm talking about type of variable handled. Why is it *mut? it might be just bool type I guess.
Also I can't create mut pointer for boolean type is Rust.

**Comment by pravic** [comment]
Because of `/*out*/ BOOL* handled` - it is **out** argument.

> Also I can't create mut pointer for boolean type is Rust.
```rust
let mut handled = false as BOOL;
let params = BEHAVIOR_EVENT_PARAMS::default();
let ok = SciterFireEvent(&params, false as BOOL, &mut handled);
if ok == SCDOM_RESULT::OK && handled {
  // no error and behavior event was handled by element
}
```

**Comment by pravic** [comment]
Done in [this](https://github.com/pravic/rust-sciter/commit/0b7069c5c54b0517a3cc58c4ef8aea588b584b6f) and [this](https://github.com/pravic/rust-sciter/commit/53ede914a2fc4feef0905061efe1fffc249c7e93) commits.

However I found that send event feature mixes source and target elements, asked about it here: http://sciter.com/forums/topic/confusing-scitersendevent-k/.

**Comment by pravic** [comment]
But in general, why do you need this functionality in native code? Its easier (and better) to work with DOM via script, which can ask the native app about data and notify it about events.

**Comment by a-nigredo** [comment]
A goal was studying Rust but finally I use script;)

**Comment by pravic** [comment]
You can study it providing high-level logic and data in app, leaving UI-related operations to UI level.

**Comment by a-nigredo** [comment]
yeap, that's why I migrate to tiscript

**Comment by pravic** [comment]
Enjoy then :)
